### ISSUE TITLE
How do I assign a keybinding?

### ISSUE THREAD

**Issue by dcosson** [Ho-Wan/vscode-setting-toggle#1]
Relatively new to VSCode, but I would think I need a command name like `toggle.settingToggle` in order to map the toggle to a keybinding? Nothing like that is documented in the readme.

**Comment by Ho-Wan** [comment]
You can assign keybindings using the VS code 'keyboard shortcuts' interface, and searching for the name of the extension. See screenshot below, hope this helps. I may add this to the documentation to help others also.

![image](https://user-images.githubusercontent.com/32593151/47117947-bc6f4380-d25d-11e8-8b45-9d4faffc91a7.png)

You can also copy and paste the following into your keybindings.json file, and replace the keys as required.
```
    {
        "key": "ctrl+shift+alt+t",
        "command": "extension.toggle"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "extension.toggle_s1"
    },
    {
        "key": "ctrl+shift+alt+2",
        "command": "extension.toggle_s2"
    }
```

**Comment by dcosson** [comment]
Perfect, thank you!

Might be nice to add this to the README too.
