### ISSUE TITLE
Support for nested settings (language specific)

### ISSUE THREAD

**Issue by lkolchin** [ho-wan/vscode-setting-toggle#10]
Hi,

It seems that there is no support for nested setting such as:
```
   "[terraform]": {
        "editor.codeLens": false
      },
```

How can I set a toggle for such a setting?

**Comment by ho-wan** [comment]
Thanks for raising this issue. Unfortunately nested settings is not supported at the moment.

**Comment by ho-wan** [comment]
@lkolchin language specific settings are now supported as of v1.5.1 https://github.com/ho-wan/vscode-setting-toggle/pull/12
