### ISSUE TITLE
Toggle Single Column or toggle short-cuts ?

### ISSUE THREAD

**Issue by SheepDomination** [Ho-Wan/vscode-setting-toggle#2]
`view>Single Column layout editor` does not have a command ? Can it still be used with *toggle* ? Rather can I toggle two keyboard short-cuts ?

**Comment by Ho-Wan** [comment]
View> Single Column layout editor is already a command, so it does not need to be used with toggle. This extension only works with settings that can be adjusted in the 'settings.json' file.

To split the editor, there is a default keybinding of 'ctrl + \  ' (windows).
You can bind the command 'Single Column layout editor' using the VS code keybindings options.

**Comment by SheepDomination** [comment]
I understand there are keyboard short-cuts; although I want one keyboard short-cut which using *Toggle* will toggle between single column and split column; that is possible ?
