### ISSUE TITLE
Toggle between splitting and closing tab

### ISSUE THREAD

**Issue by SheepDomination** [Ho-Wan/vscode-setting-toggle#3]
I'm not sure if this is completely possible.  I want to toggle between splitting a selected tab *right* and with the selected tab in split view; to close the tab. This is my settings for *setting-toggle*;
```
   "toggle.settingTitle":"workbench.action.splitEditorRight",
    "toggle.settingState1": "workbench.action.closeActiveEditor",
    "toggle.settingState2": "workbench.action.splitEditorRight",
```

**Comment by Ho-Wan** [comment]
I don't believe this is possible using the extension. One way would be to bind the actions to keys.

**Comment by SheepDomination** [comment]
I assigned `workbench.action.splitEditorRight` to a keyboard short-cut and simply left `workbench.action.closeActiveEditor` as the default keyboard short-cut.  Although Toggle keys is still not working ?

**Comment by Ho-Wan** [comment]
This extension only allows toggle of setting state (eg. 'on' or 'off', etc.), it does not dispatch actions. So you can't trigger a `closeActiveEditor` action using this extension
