### ISSUE TITLE
Toggle Between Settings ?

### ISSUE THREAD

**Issue by SheepDomination** [Ho-Wan/vscode-setting-toggle#4]
Can Setting Toggle, Toggle between settings ?

**Comment by Ho-Wan** [comment]
No, cannot toggle multiple settings at the same time.

If you mean toggling a string, then you can do something like this:
```
    "editor.wordWrap": "off",
    "toggle.settingTitle": "editor.wordWrap",
    "toggle.settingState1": "off",
    "toggle.settingState2": "wordWrapColumn",
```
if the current setting value matches the string, it gets toggled to the opposing value.

**Comment by SheepDomination** [comment]
How about a setting which only exists within the `settings.json` file ?

**Comment by Ho-Wan** [comment]
> How about a setting which only exists within the `settings.json` file ?

Yes, it should work, that's the purpose of this extension. If it doesn't work, can you provide an example?

**Comment by SheepDomination** [comment]
I may be missing a setting option ?
```
"toggle.settingTitle": "workbench.action.python.jediEnabled": false,
    "toggle.setting1Title": "workbench.action.python.jediEnabled":true,
```

**Comment by Ho-Wan** [comment]
Try adding this to your settings.json: (whatever the name of the setting is).
It will toggle boolean values by default.

```
"toggle.settingTitle": "workbench.action.python.jediEnabled",
```

**Comment by SheepDomination** [comment]
> Try adding this to your settings.json: (whatever the name of the setting is).
> It will toggle boolean values by default.
> 
> ```
> "toggle.settingTitle": "workbench.action.python.jediEnabled",
> ```

I get an error it is not a valid setting.

**Comment by Ho-Wan** [comment]
Well, it's only works with a real setting. You can try with:

```
"toggle.settingTitle": "editor.minimap.enabled",
```

**Comment by SheepDomination** [comment]
Could you add so I can toggle settings within the `settings.json` file ?

**Comment by Ho-Wan** [comment]
> Could you add so I can toggle settings within the `settings.json` file ?

I don't understand what you mean. Please explain issue clearly if you want it addressed.

**Comment by SheepDomination** [comment]
You mentioned that one can toggle between settings; what I want to be able to do, is toggle between settings, within the *settings.json* file.  

For example, I have a setting that changes the font within code, along with a keyboard short-cut I can change the font within the *settings.json* file any time I want, which would be changing the font; without going into the *settings.json* file to change the font.
