### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by TrevCan** [ho-wan/vscode-setting-toggle#5]
![image](https://user-images.githubusercontent.com/44383325/60737989-52e5b100-9f22-11e9-9975-a2809f6e127a.png)

The following image shows the error(s) that show when I try to click on the extension, it is not working and I believe it's because of some wrong path, since it can't find the .json file.

**Comment by TrevCan** [comment]
![image](https://user-images.githubusercontent.com/44383325/60738076-9a6c3d00-9f22-11e9-9c12-66c868db4b37.png)

**Comment by ho-wan** [comment]
> The following image shows the error(s) that show when I try to click on the extension, it is not working and I believe it's because of some wrong path, since it can't find the .json file.

Can you try creating an `settings.json` file at that specified path (you can do this by changing any of the default settings using the GUI that vs code provides now).

**Comment by TrevCan** [comment]
I think I figured it out... Is there a way I can change the file path which it is directed to? I installed somewhat a different version of vscode through a third party installer, that's why it could not find the file path

**Comment by TrevCan** [comment]
(I already have a settings.json but it's in another file path)

**Comment by ho-wan** [comment]
> I think I figured it out... Is there a way I can change the file path which it is directed to? I installed somewhat a different version of vscode through a third party installer, that's why it could not find the file path

Sorry, there isn't a way to change the file path for the settings.json file at the moment.
