### ISSUE TITLE
VS Code is not updated

### ISSUE THREAD

**Issue by jabbalaci** [ho-wan/vscode-setting-toggle#6]
Thanks a lot for this extension. I have an issue though:

I have 2 tabs open, a C# source code and settings.json. When I click on the "T" icon, settings.json is changed (toggling works), but the tab with the C# code is not updated. However, if I switch to settings.json and save it manually (Ctrl+s) and go back to the C# code tab, it's updated.

My expectation was this: when I'm on the C# code tab and press the "T" icon, I could see the changes (codelens on/off) immediately. But it's not the case right now.

**Comment by ho-wan** [comment]
Thanks for using this extension, sorry for the delayed response. If the settings.json file is open with unsaved changes, then the toggle will not work. If the settings.json file is saved or just not opened manually, then the toggle should work.

I've just pushed a new release v1.4.1 to this extension which changes how this toggle is implemented and should improve behaviour.
